apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-lpsre-management-cluster
  namespace: openshift-rbac-permissions
spec:
  clusterPermissions:
  # Some Package Operator APIs are cluster scoped,
  # so access must be granted on the whole cluster.
  - backplane-lpsre-management-cluster-cluster
  # permit get at global scope https://issues.redhat.com/browse/OSD-15997
  - view
  permissions:
  - clusterRoleName: admin
    namespacesAllowedRegex: '(^openshift-package-operator$)'
    namespacesDeniedRegex: openshift-backplane-cluster-admin
  - clusterRoleName: backplane-lpsre-management-cluster-project
    namespacesAllowedRegex: "(^uhc.*|^ocm.*|^klusterlet.*)"
    namespacesDeniedRegex: openshift-backplane-cluster-admin
  - clusterRoleName: dedicated-readers
    namespacesAllowedRegex: "(^hypershift.*|^uhc.*|^ocm.*|^klusterlet.*|^open-cluster-management.*)"
    namespacesDeniedRegex: openshift-backplane-cluster-admin
  - clusterRoleName: backplane-lpsre-admins-project
    namespacesAllowedRegex: "(^cert-manager$|^redhat-cert-manager-operator$|^hypershift.*|^open-cluster-management.*)"
    namespacesDeniedRegex: openshift-backplane-cluster-admin
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-lpsre
