apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-lpsre-management-cluster-cluster
rules:
- apiGroups:
  - package-operator.run
  resources: 
  - clusterobjectdeployments
  - clusterobjectsetphases
  - clusterobjectsets
  - clusterobjectslices
  - clusterobjecttemplates
  - clusterpackages
  - objectdeployments
  - objectsetphases
  - objectsets
  - objectslices
  - objecttemplates
  - packages
  verbs:
  - get
  - list
  - watch
  # Required to recover in case of outages.
  # e.g.
  # - finalizer stuck blocking cluster deletion
  # - data loss of child resource, breaking revision linearity
  #   (https://package-operator.run/docs/concepts/revisions/)
  # - dynamic object watch missing an event due to a bug or high load
  - update
  - patch
  - create
  - delete
- apiGroups:
  - work.open-cluster-management.io
  resources:
  - appliedmanifestworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - clusterclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.open-cluster-management.io
  resources:
  - klusterlets
  verbs:
  - get
  - list
  - watch
# SRE can view ACM Policy at cluster scope
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
# SRE can view HCP resources at cluster scope
- apiGroups:
  - hypershift.openshift.io
  - scheduling.hypershift.openshift.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
# SRE can view networking resources at cluster scope
- apiGroups:
  - networking.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
