apiVersion: batch/v1
kind: Job
metadata:
    name: osd-cluster-ready
    namespace: openshift-monitoring
spec:
    # NOTE: We're making this ridiculously high to ensure that the
    # actual code gets a chance to run to completion. However, consumers
    # should implement a sensible timeout rather than waiting forever.
    backoffLimit: 500
    template:
        metadata:
            name: osd-cluster-ready       
            annotations:
                openshift.io/required-scc: restricted-v2
        spec:
            containers:
            - name: osd-cluster-ready
              # Keep the `managed.openshift.io/version` label in sync
              # with this
              image: "quay.io/redhat-services-prod/openshift/osd-cluster-ready@sha256:c30c9159f7d196cacc0ff31e4286523f70cf7ed0fb671f2f115e93bd56ac6b1b"
            restartPolicy: OnFailure
            serviceAccountName: osd-cluster-ready
