apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-srep-rhobs-regional-cluster
rules:
# SRE can view core monitoring.rhobs resources at cluster scope
- apiGroups:
  - monitoring.rhobs
  resources:
  - alertmanagers
  - monitoringstacks
  - prometheuses
  - prometheusrules
  - thanosqueriers
  verbs:
  - get
  - list
  - watch
