apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-srep-rhobs-cluster-project
rules:
- apiGroups:
  - monitoring.rhobs
  resources:
  - alertmanagers
  - monitoringstacks
  - prometheuses
  - prometheusrules
  - thanosqueriers
  - pods
  - configmaps
  verbs:
  - get
  - list
  - watch
  - patch
  - update
  - delete
