deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
  - key: ext-managed.openshift.io/rhobs-regional-cluster
    operator: In
    values: ["true"]
  - key: api.openshift.com/fedramp
    operator: NotIn
    values: ["true"]