apiVersion: v1
kind: ConfigMap
metadata:
  name: osd-cluster-metadata
  namespace: openshift-config
data:
  api.openshift.com_ccs: "{{ fromCDLabel \"api.openshift.com/ccs\" }}"
  api.openshift.com_channel-group: "{{ fromCDLabel \"api.openshift.com/channel-group\" }}"
  api.openshift.com_environment: "{{ fromCDLabel \"api.openshift.com/environment\" }}"
  hive.openshift.io_cluster-platform: "{{ fromCDLabel \"hive.openshift.io/cluster-platform\" }}"
  hive.openshift.io_cluster-region: "{{ fromCDLabel \"hive.openshift.io/cluster-region\" }}"
