deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  resourceApplyMode: Upsert
  matchExpressions:
  - key: hive.openshift.io/version-major-minor
    operator: In
    values: ["4.18"]
  - key: api.openshift.com/gate-ocp
    operator: In
    values: ["4.19"]
