apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backplane-csm-pcap-collector
  namespace: openshift-backplane-managed-scripts
rules:
# can create cred secret for mustgathers
# Enables managed-scripts networking/pcap-collector, which requires users to be able to create/get/delete the pcap-collector-creds secret in the managed scripts ns
- apiGroups:
  - ""
  resourceNames:
  - pcap-collector-creds
  resources:
  - secrets
  verbs:
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
### END
